{% set name = "pyEDFlib" %}
{% set version = "0.1.9" %}
{% set sha256 = "2A4EFD9DD4BABE69DB59BEB8E6C72DFFE8CC954D44947C1043F86836EA04EAA2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/holgern/pyedflib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
  run:
    - python
    - numpy x.x

test:
  requires:
    - nose
  imports:
    - pyedflib
  commands:
    - conda inspect linkages -p $PREFIX pyedflib  # [not win]
    - conda inspect objects -p $PREFIX pyedflib   # [osx]

about:
  home: https://github.com/holgern/pyedflib
  license: BSD-2-Clause
  license_file: LICENSE
  dev_url: https://github.com/holgern/pyedflib
  doc_url: http://pyedflib.readthedocs.io/
  summary: 'Library to read/write EDF+/BDF+ files based on EDFlib.'

extra:
  recipe-maintainers:
    - holgern
